/**
 * Cloudflare Worker: package a DOS game folder into a js-dos (.jsdos) bundle.
 *
 * A .jsdos bundle is a ZIP archive with:
 *   - the game files at the archive root (DOSBox mounts this as drive C:)
 *   - a `.jsdos/dosbox.conf` whose [autoexec] section runs the game executable
 *
 * Routes:
 *   GET  /         -> a drag-and-drop folder-upload page
 *   POST /bundle   -> multipart form with the game files, returns <name>.jsdos
 */

import { zipSync, type Zippable } from "fflate";

const EXECUTABLE_EXTS = [".exe", ".com", ".bat"];

const DOSBOX_CONF_TEMPLATE = `[sdl]
autolock=false
[dosbox]
machine=svga_s3
captures=capture
memsize=16
[cpu]
core=auto
cputype=auto
cycles=auto
[mixer]
nosound=false
rate=44100
[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5
oplmode=auto
oplrate=44100
[speaker]
pcspeaker=true
[dos]
xms=true
ems=true
umb=true
keyboardlayout=auto
[autoexec]
echo off
mount c .
c:
{exec}
echo on

# Generated by jsdos-bundle-worker (https://js-dos.com)
`;

function extname(name: string): string {
    const dot = name.lastIndexOf(".");
    return dot < 0 ? "" : name.slice(dot).toLowerCase();
}

function stripExt(name: string): string {
    const dot = name.lastIndexOf(".");
    return dot < 0 ? name : name.slice(0, dot);
}

/** Choose the most likely "main" executable for a game folder. */
function pickExecutable(exeNames: string[], folderName: string): string {
    const lowered = new Map(exeNames.map((n) => [n.toLowerCase(), n]));
    const folderKey = folderName.toLowerCase();

    // 1. executable whose stem matches the folder name (zone66 -> zone66.exe)
    for (const ext of EXECUTABLE_EXTS) {
        const hit = lowered.get(folderKey + ext);
        if (hit) {
            return hit;
        }
    }
    // 2. any .bat launcher
    const bats = exeNames.filter((n) => n.toLowerCase().endsWith(".bat")).sort();
    if (bats.length > 0) {
        return bats[0];
    }
    // 3. first executable alphabetically
    return [...exeNames].sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()))[0];
}

/** Build the DOS command that launches the executable. */
function execCommand(exeName: string): string {
    if (extname(exeName) === ".bat") {
        return "call " + exeName; // return to shell after the batch finishes
    }
    return stripExt(exeName); // DOS runs FOO.EXE / FOO.COM by typing FOO
}

/** Normalise a path to forward slashes and drop the leading game-folder segment. */
function toArchivePath(rawPath: string): { folder: string; arc: string } {
    const parts = rawPath.replace(/\\/g, "/").split("/").filter(Boolean);
    if (parts.length > 1) {
        // e.g. "zone66/data/title.z66" -> folder "zone66", arc "data/title.z66"
        return { folder: parts[0], arc: parts.slice(1).join("/") };
    }
    return { folder: "", arc: parts[0] ?? "" };
}

async function handleBundle(request: Request): Promise<Response> {
    const form = await request.formData();
    const files = form.getAll("file").filter((f): f is File => f instanceof File);

    if (files.length === 0) {
        return new Response("No files uploaded", { status: 400 });
    }

    // Relative paths preserve the folder structure. The client sends them in a
    // parallel "paths" JSON array (webkitRelativePath); fall back to file.name.
    let paths: string[];
    try {
        const raw = form.get("paths");
        paths = typeof raw === "string" ? JSON.parse(raw) : [];
    } catch {
        paths = [];
    }

    const zippable: Zippable = {};
    const rootNames = new Set<string>();
    const topExecutables: string[] = [];
    let bundleName = (form.get("name") as string) || "";

    for (let i = 0; i < files.length; i++) {
        const file = files[i];
        const rawPath = paths[i] || file.name;
        const { folder, arc } = toArchivePath(rawPath);
        if (!arc || arc.endsWith("/")) {
            continue;
        }
        if (folder) {
            rootNames.add(folder);
        }
        if (!bundleName && folder) {
            bundleName = folder;
        }
        // Track executables that sit at the game-folder root (arc has no slash).
        if (!arc.includes("/") && EXECUTABLE_EXTS.includes(extname(arc))) {
            topExecutables.push(arc);
        }
        zippable[arc] = new Uint8Array(await file.arrayBuffer());
    }

    if (Object.keys(zippable).length === 0) {
        return new Response("No usable files in upload", { status: 400 });
    }
    if (topExecutables.length === 0) {
        return new Response(
            "No DOS executable (.exe/.com/.bat) found at the folder root",
            { status: 422 },
        );
    }

    // A single dropped folder is expected; if several, just name it "bundle".
    if (!bundleName) {
        bundleName = rootNames.size === 1 ? [...rootNames][0] : "bundle";
    }

    const exe = pickExecutable(topExecutables, bundleName);
    const conf = DOSBOX_CONF_TEMPLATE.replace("{exec}", execCommand(exe)).replace(
        /\n/g,
        "\r\n",
    );
    zippable[".jsdos/dosbox.conf"] = new TextEncoder().encode(conf);

    const zipped = zipSync(zippable, { level: 6 });
    const safeName = bundleName.replace(/[^a-zA-Z0-9._-]/g, "_") || "bundle";

    return new Response(zipped, {
        headers: {
            "Content-Type": "application/octet-stream",
            "Content-Disposition": `attachment; filename="${safeName}.jsdos"`,
            "X-Bundle-Executable": exe,
        },
    });
}

export default {
    async fetch(request: Request): Promise<Response> {
        const url = new URL(request.url);

        if (request.method === "POST" && url.pathname === "/bundle") {
            try {
                return await handleBundle(request);
            } catch (e: any) {
                return new Response("Failed to build bundle: " + (e?.message ?? e), {
                    status: 500,
                });
            }
        }

        if (request.method === "GET" && url.pathname === "/") {
            return new Response(INDEX_HTML, {
                headers: { "Content-Type": "text/html; charset=utf-8" },
            });
        }

        return new Response("Not found", { status: 404 });
    },
};

const INDEX_HTML = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Make a .jsdos bundle</title>
<style>
  :root { color-scheme: light dark; }
  body { font: 16px/1.5 system-ui, sans-serif; max-width: 640px; margin: 3rem auto; padding: 0 1rem; }
  h1 { font-size: 1.4rem; }
  #drop { border: 2px dashed currentColor; border-radius: 12px; padding: 3rem 1rem;
          text-align: center; opacity: .8; cursor: pointer; transition: opacity .15s; }
  #drop.over { opacity: 1; background: rgba(127,127,127,.12); }
  #log { margin-top: 1rem; white-space: pre-wrap; font-family: ui-monospace, monospace; }
  input[type=file] { display: none; }
  a.btn { display: inline-block; margin-top: 1rem; padding: .5rem 1rem;
          border: 1px solid currentColor; border-radius: 8px; text-decoration: none; }
</style>
</head>
<body>
<h1>Package a DOS game folder into a .jsdos bundle</h1>
<p>Pick a folder containing a DOS game (its .exe/.com/.bat plus data files).
It is zipped into a ready-to-run <code>.jsdos</code> bundle for
<a href="https://js-dos.com">js-dos</a>.</p>

<label id="drop">
  <input type="file" id="picker" webkitdirectory multiple>
  Click to choose a folder — or drag &amp; drop it here
</label>
<div id="log"></div>

<script>
const drop = document.getElementById("drop");
const picker = document.getElementById("picker");
const log = document.getElementById("log");

picker.addEventListener("change", () => upload([...picker.files]));

drop.addEventListener("dragover", (e) => { e.preventDefault(); drop.classList.add("over"); });
drop.addEventListener("dragleave", () => drop.classList.remove("over"));
drop.addEventListener("drop", async (e) => {
  e.preventDefault();
  drop.classList.remove("over");
  const files = await filesFromDataTransfer(e.dataTransfer);
  upload(files);
});

// Recursively read a dropped directory into File objects with relative paths.
async function filesFromDataTransfer(dt) {
  const out = [];
  const walk = async (entry, prefix) => {
    if (entry.isFile) {
      const file = await new Promise((res) => entry.file(res));
      file._rel = prefix + entry.name;
      out.push(file);
    } else if (entry.isDirectory) {
      const reader = entry.createReader();
      const entries = await new Promise((res) => reader.readEntries(res));
      for (const child of entries) await walk(child, prefix + entry.name + "/");
    }
  };
  const items = [...dt.items].map((i) => i.webkitGetAsEntry()).filter(Boolean);
  for (const item of items) await walk(item, "");
  return out;
}

async function upload(files) {
  if (!files.length) return;
  log.textContent = "Uploading " + files.length + " file(s)…";
  const form = new FormData();
  const paths = [];
  for (const f of files) {
    const rel = f.webkitRelativePath || f._rel || f.name;
    paths.push(rel);
    form.append("file", f, f.name);
  }
  form.append("paths", JSON.stringify(paths));

  try {
    const res = await fetch("/bundle", { method: "POST", body: form });
    if (!res.ok) { log.textContent = "Error: " + (await res.text()); return; }
    const blob = await res.blob();
    const dispo = res.headers.get("Content-Disposition") || "";
    const name = (dispo.match(/filename="([^"]+)"/) || [])[1] || "bundle.jsdos";
    const exe = res.headers.get("X-Bundle-Executable");
    const href = URL.createObjectURL(blob);
    log.innerHTML = "Bundle ready" + (exe ? " (runs " + exe + ")" : "") +
      '.<br><a class="btn" href="' + href + '" download="' + name + '">Download ' + name + "</a>";
  } catch (err) {
    log.textContent = "Error: " + err;
  }
}
</script>
</body>
</html>`;
