/**
 * Shared js-dos bundling helpers, used by both the Worker (runtime, upload
 * path) and the build script (scripts/build-bundles.mjs, folder path).
 *
 * A .jsdos bundle is a ZIP with the game files at the archive root and a
 * `.jsdos/dosbox.conf` whose [autoexec] section runs the game executable.
 */

import { zipSync } from "fflate";

export const EXECUTABLE_EXTS = [".exe", ".com", ".bat"];

const DOSBOX_CONF_TEMPLATE = `[sdl]
autolock=false
[dosbox]
machine=svga_s3
captures=capture
memsize=16
[cpu]
core=auto
cputype=auto
cycles=auto
[mixer]
nosound=false
rate=44100
[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5
oplmode=auto
oplrate=44100
[speaker]
pcspeaker=true
[dos]
xms=true
ems=true
umb=true
keyboardlayout=auto
[autoexec]
echo off
mount c .
c:
{exec}
echo on

# Generated by jsdos-bundle-worker (https://js-dos.com)
`;

export function extname(name) {
    const dot = name.lastIndexOf(".");
    return dot < 0 ? "" : name.slice(dot).toLowerCase();
}

export function stripExt(name) {
    const dot = name.lastIndexOf(".");
    return dot < 0 ? name : name.slice(0, dot);
}

/** Choose the most likely "main" executable for a game folder. */
export function pickExecutable(exeNames, folderName) {
    const lowered = new Map(exeNames.map((n) => [n.toLowerCase(), n]));
    const folderKey = folderName.toLowerCase();

    // 1. executable whose stem matches the folder name (zone66 -> zone66.exe)
    for (const ext of EXECUTABLE_EXTS) {
        const hit = lowered.get(folderKey + ext);
        if (hit) {
            return hit;
        }
    }
    // 2. any .bat launcher
    const bats = exeNames.filter((n) => n.toLowerCase().endsWith(".bat")).sort();
    if (bats.length > 0) {
        return bats[0];
    }
    // 3. first executable alphabetically
    return [...exeNames].sort((a, b) => a.toLowerCase().localeCompare(b.toLowerCase()))[0];
}

/** Build the DOS command that launches the executable. */
export function execCommand(exeName) {
    if (extname(exeName) === ".bat") {
        return "call " + exeName; // return to shell after the batch finishes
    }
    return stripExt(exeName); // DOS runs FOO.EXE / FOO.COM by typing FOO
}

/** Render a .jsdos/dosbox.conf that launches `exeName`, with CRLF endings. */
export function dosboxConf(exeName) {
    return DOSBOX_CONF_TEMPLATE.replace("{exec}", execCommand(exeName)).replace(/\n/g, "\r\n");
}

/**
 * Build a .jsdos bundle from a map of archive-path -> Uint8Array.
 *
 * `files` must contain the game files keyed by their path relative to the game
 * folder root (e.g. "zone66.exe", "data/title.z66"). Executables at the root
 * are auto-detected; the generated .jsdos/dosbox.conf is added automatically.
 *
 * Returns { zip: Uint8Array, exe: string }. Throws if no root executable found.
 */
export function buildBundle(files, folderName) {
    const rootExecutables = Object.keys(files).filter(
        (p) => !p.includes("/") && EXECUTABLE_EXTS.includes(extname(p)),
    );
    if (rootExecutables.length === 0) {
        throw new Error("No DOS executable (.exe/.com/.bat) found at the folder root");
    }

    const exe = pickExecutable(rootExecutables, folderName);
    const zippable = { ...files };
    zippable[".jsdos/dosbox.conf"] = new TextEncoder().encode(dosboxConf(exe));

    return { zip: zipSync(zippable, { level: 6 }), exe };
}
