// Autogenerated
// -------------
// gulpfile.js --> generateBuildInfo

export const Build = {
    version: "6.22-cc29ba346400bdb29f459d8d502056d1415e9ce4",
    wasmSize: 2167540,
    jsSize:  503536,
};
