// Autogenerated
// -------------
// gulpfile.js --> generateBuildInfo

export const Build = {
    version: "6.22-74fd251bfd3599cf30b2d4a78e0507aaa2bd268d",
    wasmSize: 2167076,
    jsSize:  503282,
};
