org: caiiiycuk
app: jsdos-backend
service: jsdos-v7

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  memorySize: 256
  versionFunctions: false
  environment:
    NETWORKING_TABLE: "v2_r1_dznetworking"
    PUT_CURL: "jjs-putCurl"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListBucket
      Resource:
        - "arn:aws:s3:::doszone-uploads"
    - Effect: Allow
      Action:
        - s3:Get*
        - s3:Put*
      Resource:
        - "arn:aws:s3:::doszone-uploads/*"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource:
        - "arn:aws:lambda:${opt:region, self:provider.region}:*:function:${self:provider.environment.PUT_CURL}"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.NETWORKING_TABLE}"

functions:
  getTokenCost: 
    handler: src/networking/get-token-cost.getTokenCost
    name: jsdos-getTokenCost
    events:
      - http:
          path: /token/cost/get
          method: get
          cors: true
  getFreeToken:
    handler: src/networking/get-free-token.getFreeToken
    name: jsdos-getFreeToken
    events:
      - http:
          path: /token/free/get
          method: get
          cors: true
  getTokenInfo:
    handler: src/networking/get-token-info.getTokenInfo
    name: jsdos-getTokenInfo
    events:
      - http:
          path: /token/info/get
          method: get
          cors: true
  personalPut:
    handler: src/personal-put.personalPut
    name: jsdos-personalPut
    events:
      - http:
          path: /personal/put
          method: post
          cors: true
  personalAcl:
    handler: src/personal-acl.personalAcl
    name: jsdos-personalAcl
    events:
      - http:
          path: /personal/acl
          method: post
          cors: true

resources:
  Resources:
    dznetworking:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: key
            AttributeType: S
          -
            AttributeName: day
            AttributeType: N
        KeySchema:
          -
            AttributeName: key
            KeyType: HASH
        GlobalSecondaryIndexes:
          -
            IndexName: day
            KeySchema:
            -
              AttributeName: day
              KeyType: HASH
            Projection:
              ProjectionType: ALL
        TableName: ${self:provider.environment.NETWORKING_TABLE}
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-plugin-typescript
