org: caiiiycuk
app: jsdos-backend
service: jsdos-v7

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  memorySize: 256
  versionFunctions: false
  environment:
    NETWORKING_TABLE: "v2_r1_dznetworking"
    PUT_CURL: "jjs-putCurl"
    RUN_INSTANCE: "jjs-runInstanceV2"
    CREATE_TOKEN: "jjs-createToken"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListBucket
      Resource:
        - "arn:aws:s3:::doszone-uploads"
    - Effect: Allow
      Action:
        - s3:Get*
        - s3:Put*
      Resource:
        - "arn:aws:s3:::doszone-uploads/*"
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource:
        - "arn:aws:lambda:${opt:region, self:provider.region}:*:function:${self:provider.environment.PUT_CURL}"
        - "arn:aws:lambda:${opt:region, self:provider.region}:*:function:${self:provider.environment.RUN_INSTANCE}"
        - "arn:aws:lambda:${opt:region, self:provider.region}:*:function:${self:provider.environment.CREATE_TOKEN}"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.NETWORKING_TABLE}"

functions:
  createToken:
    handler: src/networking/create-token.createToken
    name: jsdos-createToken
    description: Create NEW token 
    events:
      - http:
          path: /token/create
          method: POST
          cors: true
          integration: lambda
          request:
            passThrough: NEVER
            schemas:
              application/json: ${file(src/networking/create-token.schema.json)}
  addTokenFreeTierTime:
    handler: src/networking/add-token-free-tier-time.addTokenFreeTierTime
    name: jsdos-addTokenFreeTierTime
    events:
      - http:
          path: /token/add/free
          method: POST
          cors: true
          integration: lambda
          request:
            passThrough: NEVER
            schemas:
              application/json: ${file(src/networking/add-token-free-tier-time.schema.json)}
  addTokenTime:
    handler: src/networking/add-token-time.addTokenTime
    name: jsdos-addTokenTime
  getTokenInfo:
    handler: src/networking/get-token-info.getTokenInfo
    name: jsdos-getTokenInfo
    events:
      - http:
          path: /token/info/get
          method: get
          cors: true
          integration: lambda
          request:
            passThrough: NEVER
            parameters:
              querystrings:
                token: true
  startIpx:
    handler: src/networking/ipx/start-ipx.startIpx
    name: jsdos-startIpx
    events:
      - http:
          path: /token/ipx/start
          method: get
          cors: true
  putIpxAddress:
    handler: src/networking/ipx/put-ipx-address.putIpxAddress
    name: jsdos-putIpxAddress
    events:
      - http:
          path: /token/ipx/address/put
          method: put
          cors: true
  stopIpx:
    handler: src/networking/ipx/stop-ipx.stopIpx
    name: jsdos-stopIpx
    events:
      - http:
          path: /token/ipx/stop
          method: post
          cors: true
  testIpx:
    handler: src/networking/ipx/test-ipx.testIpx
    name: jsdos-testIpx
    events:
      - http:
          path: /token/ipx/test
          method: get
          cors: true
          integration: lambda
          request:
            passThrough: NEVER
            parameters:
              querystrings:
                token: true
                arn: true
  personalPut:
    handler: src/personal-put.personalPut
    name: jsdos-personalPut
    events:
      - http:
          path: /personal/put
          method: post
          cors: true
  personalAcl:
    handler: src/personal-acl.personalAcl
    name: jsdos-personalAcl
    events:
      - http:
          path: /personal/acl
          method: post
          cors: true
  checkoutCreateToken:
    handler: src/checkout/create-token.createToken
    name: jsdos-checkout-createToken
    description: Create new token for checkout
    events:
      - http:
          path: /checkout/token/create
          method: post
          cors: true
          integration: lambda
          request:
            passThrough: NEVER
            schemas:
              application/json: ${file(src/checkout/create-token.schema.json)}

resources:
  Resources:
    dznetworking:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: key
            AttributeType: S
          -
            AttributeName: day
            AttributeType: N
        KeySchema:
          -
            AttributeName: key
            KeyType: HASH
        GlobalSecondaryIndexes:
          -
            IndexName: day
            KeySchema:
            -
              AttributeName: day
              KeyType: HASH
            Projection:
              ProjectionType: ALL
        TableName: ${self:provider.environment.NETWORKING_TABLE}
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-plugin-typescript
