
// Autogenerated
// -------------
// gulpfile.ts/wasm.ts --> generateBuildInfo

export const Build = {
    short: "0.73.9",
    version: "0.73.9 (8dd6a9be3fd1f818af5862d3c3c93443)",
    buildSeed: 1673509944011,
};
