// Autogenerated
// -------------
// gulpfile.js --> generateBuildInfo

export const Build = {
    version: "6.22.59 (85501cd3c6d657c19d79f5676413c9e2)",
    jsVersion: "c91aba6d87b543aa4887dd6d9d4e5f922a10b8f2",
    wasmJsSize:  130499,
    wasmVersion: "e63a1b541e220ad2f5fbaf8706e5d319",
    wasmSize: 1206972,
    jsSize:  0,
    buildSeed:  1584885135674,
};
