// Autogenerated
// -------------
// gulpfile.js --> generateBuildInfo

export const Build = {
    version: "6.22.47 (7163c7f9c4e852975b78eb2e5cb56bb3)",
    jsVersion: "52e79778acd837ee7b6eb5d484e16bd429646ef0",
    wasmJsSize:  199778,
    wasmVersion: "69c3be525f3290f3e69512ede0ba8831",
    wasmSize: 1809313,
    jsSize:  6651975,
    buildSeed:  1573399260553,
};
