// Autogenerated
// -------------
// gulpfile.js --> generateBuildInfo

export const Build = {
    version: "6.22.59 (f847b66eef6731ef1fb3cac88d76b6bc)",
    jsVersion: "e48b52eee9ec34322f6d5ac68edc56f854b143f6",
    wasmJsSize:  343675,
    wasmVersion: "374a0ca465a4911cb444d8834c67ebe0",
    wasmSize: 1749814,
    buildSeed:  1586919002853,
};
