// Autogenerated
// -------------
// gulpfile.js --> generateBuildInfo

export const Build = {
    version: "6.22.59 (213be7955233feb1f5288a59a7aac1ce)",
    jsVersion: "abf4b3dde3cc49bd51887b188cc3041a13137764",
    wasmJsSize:  173730,
    wasmVersion: "a5857c6a92fc6e9a72bd76d6a1df7af1",
    wasmSize: 1383275,
    buildSeed:  1587353829858,
};
