// Autogenerated
// -------------
// gulpfile.js --> generateBuildInfo

export const Build = {
    version: "6.22.59 (8869d07ba34ec77ad5b6d0e2c1cb33cd)",
    jsVersion: "fa578d131f68dd71f624f86e709be35950a321c0",
    wasmJsSize:  174450,
    wasmVersion: "a77a550946416473583d331c3b067257",
    wasmSize: 1375783,
    buildSeed:  1587609874010,
};
