
// Autogenerated
// -------------
// gulpfile.ts/wasm.ts --> generateBuildInfo

export const Build = {
    version: "0.0.44 (5637e0d335096ad22cca2648ed4f97ae)",
    buildSeed: 1611200329314,
    "wdirect.wasm": {
        "size": 1535611,
        "gzSize": 501140
    },
    "wdirect.js": {
        "size": 122166,
        "gzSize": 31520
    },
    "wlibzip.wasm": {
        "size": 106264,
        "gzSize": 52501
    },
    "wlibzip.js": {
        "size": 101646,
        "gzSize": 26154
    },
    "wworker.wasm": {
        "size": 1823934,
        "gzSize": 534302
    },
    "wworker.js": {
        "size": 258016,
        "gzSize": 62239
    }
,
};
