
// Autogenerated
// -------------
// gulpfile.ts/wasm.ts --> generateBuildInfo

export const Build = {
    version: "0.0.45 (3e63a0f61d3c2eef207d0175a01aee16)",
    buildSeed: 1611725390689,
    "wdirect.wasm": {
        "size": 1535927,
        "gzSize": 501316
    },
    "wdirect.js": {
        "size": 122166,
        "gzSize": 31520
    },
    "wlibzip.wasm": {
        "size": 106264,
        "gzSize": 52501
    },
    "wlibzip.js": {
        "size": 101646,
        "gzSize": 26154
    },
    "wworker.wasm": {
        "size": 1824371,
        "gzSize": 534683
    },
    "wworker.js": {
        "size": 258016,
        "gzSize": 62239
    }
,
};
