
// Autogenerated
// -------------
// gulpfile.ts/wasm.ts --> generateBuildInfo

export const Build = {
    version: "0.0.40 (2b7f160db952df0f379cc42e46cc130a)",
    buildSeed: 1610300227718,
    "wdirect.wasm": {
        "size": 1452400,
        "gzSize": 484932
    },
    "wdirect.js": {
        "size": 125930,
        "gzSize": 32024
    },
    "wlibzip.wasm": {
        "size": 106260,
        "gzSize": 51960
    },
    "wlibzip.js": {
        "size": 101459,
        "gzSize": 26168
    },
    "wworker.wasm": {
        "size": 1735004,
        "gzSize": 515927
    },
    "wworker.js": {
        "size": 258502,
        "gzSize": 62414
    }
,
};
